spring:
  application:
    name: study-kafka-producer-app

  kafka:
    bootstrap-servers: localhost:30092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      transaction-id-prefix: tx
      config:
        enable-idempotence: true
      retries: 2100000000
    listener:
      ack-mode: manual
server:
  port: 8082
