spring:
  application:
    name: study-kafka-producer-app
  datasource:
    hikari:
      url: jdbc:postgresql://jerry.world:32222
      driver-class-name: org.postgresql.Driver
      username: test
      password: test
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:30092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      transaction-id-prefix: tx
      config:
        enable-idempotence: true
      retries: 2100000000
    listener:
      ack-mode: manual
server:
  port: 8082
